id: P3693362B
initial_creation_type: input
source_metadata:
  title: Commentaries on philosophical treatises
  parent: 3. Various collections
  source: https://sakyalibrary.com
  bases:
    4cc2:
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པའི་རྒྱན།
      author: ནཱ་ལནྡྲའི་མཁན་རབས་གསུམ་པ་དགེ་བ་རྒྱལ་མཚན།
      base_file: 4cc2.txt
      order: 1
    cd78:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར།
      author: ངོར་པའི་མཁན་རབས་གསུམ་པ་འཇམ་དབྱངས་ཤེས་རབ་རྒྱལ་མཚན།
      base_file: cd78.txt
      order: 2
    f626:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་དཀའ་བའི་གནས་རྣམ་པར་འབྱེད་པ་ཞིབ་མོ་རྣམ་ཐག
      author: གློ་བོ་མཁན་ཆེན་བསོད་ནམས་ལྷུན་གྲུབ།
      base_file: f626.txt
      order: 3
    6d85:
      title: སོ་སོར་ཐར་པའི་མདོའི་ལེགས་བཤད། འདུལ་བའི་སྡེ་སྣོད་མཛེས་པར་བྱེད་པའི་རྒྱན།
      author: བླ་མ་དམ་པའི་སློབ་མ་སྤོས་ཁང་པ་རིན་ཆེན་རྒྱལ་མཚན།
      base_file: 6d85.txt
      order: 4
    b1cd:
      title: རྒྱལ་ཡུམ་སྙིང་པོའི་རྣམ་བཤད་ཉིན་བྱེད་དབང་པོ།
      author: འཇམ་དབྱངས་ཀུན་དགའ་ཆོས་བཟང་གི་སློབ་མ་གཞུང་བརྒྱ་པ་དངོས་གྲུབ་དཔལ་འབར།
      base_file: b1cd.txt
      order: 5
    ba10:
      title: ས་པཎ་གྱི་གསུང་སྒྲོས་ཟིན་བྲིས་མཛད་པའི་སྤྱོད་འཇུག་འགྲེལ་པ་འཇམ་དཔལ་ཞལ་ལུང་།
      author: ལྷོ་པ་ཀུན་མཁྱེན་རིན་ཆེན་དཔལ།
      base_file: ba10.txt
      order: 6
    ce57:
      title: དབུས་མཐའ་རྣམ་འབྱེད་ཀྱི་འགྲེལ་པ་དབུ་མའི་རྒྱན།
      author: བླ་མ་དམ་པའི་སློབ་མ་གནས་ཕྲུག་པ་བློ་གྲོས་མཚུངས་མེད།
      base_file: ce57.txt
      order: 7
    0d7d:
      title: ས་ལམ་གྱི་རྣམ་པར་གཞག་པ་དགོངས་པ་གསལ་བའི་ཉི་འོད།
      author: ཀུན་མཁྱེན་གྱི་སློབ་མ་རྭ་བན་ཡོན་ཏན་འབྱུང་གནས།
      base_file: 0d7d.txt
      order: 8
    f498:
      title: རྒྱུད་བླ་མའི་བསྟན་བཅོས་ཀྱི་ངེས་དོན་གསལ་བར་བྱེད་པ་རིན་པོ་ཆེའི་སྒྲོན་མེ།
      author: གནས་ཕྲུག་པ།
      base_file: f498.txt
      order: 9
    12c7:
      title: རྒྱུད་བླ་མའི་རྣམ་བཤད་ངེས་དོན་རབ་གསལ་སྣང་བ།
      author: ས་བཟང་མ་ཏི་པཎ་ཆེན།
      base_file: 12c7.txt
      order: 10
    b824:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་ཚར་གཅད་དང་ལྟག་ཆོད་བརྟག་པའི་རྣམ་པར་བཤད་པ་རྩོད་པའི་རྒྱན།
      author: ཐུབ་བསྟན་ཡངས་པ་ཅན་གྱི་མཁན་པོ་དབང་ཕྱུག་དཔལ་བཟང་།
      base_file: b824.txt
      order: 11
    7fd7:
      title: འཕགས་གསུམ་རྟོགས་རིགས།
      author: ཀུན་མཁྱེན་གཡག་པ།
      base_file: 7fd7.txt
      order: 12
    181b:
      title: ཆོས་དང་ཆོས་མིན་པ་རྣམ་པར་འབྱེད་པའི་བསྟན་བཅོས་སྡོམ་གསུམ་རབ་དབྱེ་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: 181b.txt
      order: 13
    1f96:
      title: སྡོམ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ་ཞེས་བྱ་བ་ལས་སྐབས་གཉིས་པའི་རྣམ་པར་བཤད་པ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: 1f96.txt
      order: 14
    1fe0:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ་ལས་སྐབས་གསུམ་པའི་རྣམ་པར་བཤད་པ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: 1fe0.txt
      order: 15
    a170:
      title: སྡོམ་གསུམ་རྣམ་བཤད་རྒྱུད་བཞི་མཛེས་རྒྱན།
      author: མང་ཐོས་སློབ་མ་རིན་སྡིང་པ་ནམ་མཁའ་རྒྱལ་མཚན།
      base_file: a170.txt
      order: 16
    a8e6:
      title: དབུ་མའི་སྤྱི་དོན་ལུང་རིགས་མཛེས་པར་བྱེད་པའི་རྒྱན།
      author: མང་ཐོས་སློབ་མ་བྱ་གཤོངས་མཁན་པོ་འཇམ་དབྱངས་དགའ་བའི་བཤེས་གཉེན།
      base_file: a8e6.txt
      order: 17
    db7d:
      title: སུམ་ཅུ་པ་དང་ཉི་ཤུ་པའི་རབ་ཏུ་བྱེད་པ།
      author: པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
      base_file: db7d.txt
      order: 18
    df99:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་དཀའ་འགྲེལ་དང་ལུང་སྦྱོར་མདོར་བསྡུས་འཇམ་དབྱངས་བླ་མའི་དགོངས་གསལ།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: df99.txt
      order: 19
    942c:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་ལས་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལེའུའི་འགྲེལ་བ་གཞུང་དོན་འཁྲུལ་མེད་གསལ་བའི་ཉི་འོད།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: 942c.txt
      order: 20
    ad50:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་བསྡུས་དོན་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་།
      author: ཀུན་དགའ་རྣམ་རྒྱལ།
      base_file: ad50.txt
      order: 21
    ea9c:
      title: ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་ཚིག་དོན་རབ་གསལ།
      author: དངོས་གྲུབ་དཔལ་འབར།
      base_file: ea9c.txt
      order: 22
    3e5d:
      title: རྣལ་འབྱོར་སྤྱོད་པ་བཞི་བརྒྱ་པའི་དེ་ཁོ་ན་ཉིད་གསལ་བར་བྱེད་པ་རིན་པོ་ཆེའི་སྒྲོན་མེ།
      author: གྲགས་པ་བཟང་པོ།
      base_file: 3e5d.txt
      order: 23
    f249:
      title: སྡེ་དགེ་རྒྱལ་པོས་མཛད་པའི་གྲུབ་མཐའི་སྡོམ་ཚིག་བཞུགས།
      author: སྡེ་དགེ་རྒྱལ་པོ།
      base_file: f249.txt
      order: 24
    d13c:
      title: སྡེ་དགེ་རྒྱལ་པོས་མཛད་པའི་གྲུབ་མཐའ་བཞི་དང་རྒྱུད་སྡེ་བཞི་ཡི་རྣམ་གཞག་བསྟན་པའི་སྙིང་པོ་སྡོམ་པ་གསུམ་གྱི་དོན་གཞི་ལམ་འབྲས་གསུམ་གྱི་གནད་བསྡུས་ཞར་བྱུང་བོད་ཀྱི་གྲུབ་མཐའི་ལོ་རྒྱུས་བཅས་ལྷན་ཅིག་ཏུ་བཀོད་པ་མདོ་སྔགས་ཆོས་ཚུལ་སྙིང་པོའི་གསལ་བྱེད་མ་རིག་མུན་པ་སེལ་བའི་དཔལ་ལྡན་འོད་ཟེར་བརྒྱ་པ་སྐལ་བཟང་བློ་ཡི་པད་ཚལ་བཞད་པ་དོན་གཉིས་ལྷུན་གྱིས་གྲུབ་པའི་ལམ་བཟང་ཞེས་བྱ་བ།
      author: སྡེ་དགེ་རྒྱལ་པོ།
      base_file: d13c.txt
      order: 25
    de4e:
      title: བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བརྗོད་བྱའི་གཙོ་བོ་དོན་བདུན་ཅུའི་རྣམ་བཤད་ངོ་མཚར་འོད་ཟེར་གྱི་འཕྲེང་བ།
      author: གྲགས་པ་ཐོགས་མེད།
      base_file: de4e.txt
      order: 26
    8a54:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བ་ལས་གནས་གསུམ་གསལ་བྱེད།
      author: ཀུན་དགའ་ཆོས་བཟང་།
      base_file: 8a54.txt
      order: 27
    a555:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་སྤྱི་དོན་སྡོམ་གསུམ་གནད་ཀྱི་གསལ་བྱེད།
      author: ཀུན་དགའ་ཆོས་བཟང་།
      base_file: a555.txt
      order: 28
    6dac:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་སོ་ཐར་སྡོམ་པའི་རྣམ་བཤད།
      author: དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: 6dac.txt
      order: 29
    ec5f:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་བྱང་སེམས་སྡོམ་པའི་རྣམ་བཤད།
      author: དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: ec5f.txt
      order: 30
    b854:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་སྔགས་སྡོམ་གྱི་རྣམ་བཤད།
      author: དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: b854.txt
      order: 31
    b388:
      title: ཚད་མའི་རྟགས་རིགས་པའི་སྐོར་གཏན་ལ་འབེབས་པར་བྱེད་པ་སྡེ་བདུན་སྒོ་བརྒྱ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡེའུ་མིག
      author: བློ་གཏེར་དབང་པོ།
      base_file: b388.txt
      order: 32
    a5cd:
      title: དག་ཡིག་ལི་ཤིའི་གུར་ཁང་།
      author: ཞྭ་ལུ་སྐྱོགས་སྟོན།
      base_file: a5cd.txt
      order: 33
created_at: '2022-04-06T17:55:44.005296'
last_modified_at: '2022-04-06T17:55:44.005305'
